# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "debian/bookworm64" # Box Debian 12

  #Router
  config.vm.define "router" do |router|
    router.vm.hostname = "router" # Nombre del host
    router.vm.network "private_network", ip:"192.168.10.5", virtualbox__intnet: "red1" # Red interna
    router.vm.network "private_network", ip:"192.168.11.5", virtualbox__intnet: "red2" # Red interna
    router.vm.network "forwarded_port", guest: 80, host: 8080
    router.vm.provision "shell", path: "./scripts/iptables/router.sh"
  end
  
  #En Windows Server en Virtual box
  #DHCP y DNS
  # config.vm.define "dhcpdns" do |dhcpdns|
  #   dhcpdns.vm.network "private_network", ip:"192.168.10.10", virtualbox__intnet: "red1"  # Red interna
  #   dhcpdns.vm.hostname = "DHCPDNS"  # Nombre del host
  # end
  
  #En Windows Server en Virtual box
  #FTP
  # config.vm.define "ftp" do |ftp|
  #   ftp.vm.network "private_network", ip:"192.168.10.11", virtualbox__intnet: "red1"  # Red interna
  #   ftp.vm.hostname = "FTP"  # Nombre del host
  #   router.vm.provision "shell", path: "aprov_ftp.sh"
  # end

  #Balanceador
  config.vm.define "balanceador" do |balanceador|
    balanceador.vm.hostname = "balanceador"  # Nombre del host
    balanceador.vm.network "private_network", ip:"192.168.11.10", virtualbox__intnet: "red2"  # Red interna
    balanceador.vm.network "private_network", ip:"192.168.20.5", virtualbox__intnet: "LANinterna"  # Red interna
    balanceador.vm.provision "shell", path: "./scripts/aprovisionamiento/aprov_balanceador.sh"
    balanceador.vm.provision "shell", path: "./scripts/iptables/balanceador.sh"
  end

  #Servidor Web Backend 1
  config.vm.define "servidorweb1" do |servidorweb1|
    servidorweb1.vm.hostname = "servidorweb1"  # Nombre del host
    servidorweb1.vm.network "private_network", ip:"192.168.20.10", virtualbox__intnet: "LANinterna"  # Red interna
    servidorweb1.vm.network "private_network", ip:"192.168.30.10", virtualbox__intnet: "LANDatos"  # Red interna
    servidorweb1.vm.provision "shell", path: "./scripts/aprovisionamiento/aprov_web.sh"
    servidorweb1.vm.provision "shell", path: "./scripts/iptables/web.sh"
  end
  
  #Servidor Web Backend 2
  config.vm.define "servidorweb2" do |servidorweb2|
    servidorweb2.vm.hostname = "servidorweb2"  # Nombre del host
    servidorweb2.vm.network "private_network", ip:"192.168.20.11", virtualbox__intnet: "LANinterna"  # Red interna
    servidorweb2.vm.network "private_network", ip:"192.168.30.11", virtualbox__intnet: "LANDatos"  # Red interna
    servidorweb2.vm.provision "shell", path: "./scripts/aprovisionamiento/aprov_web.sh"
    servidorweb2.vm.provision "shell", path: "./scripts/iptables/web.sh"
  end

  #Servidor NFS
  config.vm.define "nfs" do |nfs|
    nfs.vm.hostname = "nfs"  # Nombre del host
    nfs.vm.network "private_network", ip:"192.168.30.12", virtualbox__intnet: "LANDatos"  # Red interna
    nfs.vm.provision "shell", path: "./scripts/aprovisionamiento/aprov_nfs.sh"
    nfs.vm.provision "shell", path: "./scripts/iptables/nfs.sh"
  end

  #Servidor de BBDD
 config.vm.define "sql" do |sql|
    sql.vm.hostname = "sql"  # Nombre del host
    sql.vm.network "private_network", ip:"192.168.30.5", virtualbox__intnet: "LANDatos"  # Red interna
    sql.vm.provision "shell", path: "./scripts/aprovisionamiento/aprov_sql.sh" # Script de aprovisionamiento
    sql.vm.provision "shell", path: "./scripts/iptables/sql.sh" # Script de aprovisionamiento
  end



  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Disable the default share of the current code directory. Doing this
  # provides improved isolation between the vagrant box and your host
  # by making sure your Vagrantfile isn't accessible to the vagrant box.
  # If you use this you may want to enable additional shared subfolders as
  # shown above.
  # config.vm.synced_folder ".", "/vagrant", disabled: true

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
